baseURL = 'https://d3jow2udcm31b0.cloudfront.net/'
locale = "nl-nl"
title = 'PDF Zoekmachine'
theme = [] # We gebruiken geen zwaar thema, we maken het zelf simpel.
uglyURLs = true

[params]
  s3_url = "https://d3jow2udcm31b0.cloudfront.net/"
  indexURL = 'https://d3jow2udcm31b0.cloudfront.net/index.html'

[outputs]
home = ["HTML", "RSS", "JSON"]

[minify]
  disableXML = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
